
- name: variables from prompt
  hosts: localhost 
  connection: local

  vars_prompt:
  - name: username
    prompt: what is tour username
    private: false

  - name: password
    prompt: What is your password?
    private: true

  tasks:
  - name: print the username
    ansible.builtin.debug:
     msg: "hello, Username is: {{ username }}"

