- name: variables from args
  hosts: localhost
  connection: local
  tasks:
  - name: print the course info
    ansible.builtin.debug:
     msg: "Course Name is: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ Trainer }}" 