- name: install packages using loop
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: print package  
    ansible.builtin.package:
     name: "{{ item.name }}"               #item.name is a of particular dictionary in loops
     state: "{{ item.state }}"             #item.state is a of particular dictionary in loops
    loop:
    - { name: "nginx", state: "present" }   #present installs the package
    - { name: "mysql", state: "absent" }    #absent uninstalls the package