- name: install packages using loop
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: print package  
    ansible.builtin.package:
     name: "{{ item.name }}"
     state: "{{ item.state }}"              #item is a default variable in loops
    loop:
    - { name: "nginx", state: "present" }
    - { name: "mysql", state: "absent" }